### ISSUE TITLE
Request: Green Lantern

### ISSUE THREAD

**Issue by akalata** [akalata/drupalheroes#2]

**Comment by rteijeiro** [comment]
I already have this one. Maybe it needs some work.

<img width="528" alt="screenshot_26_11_15_12_58" src="https://cloud.githubusercontent.com/assets/1265384/11422576/6cb7baa4-943d-11e5-89d3-74dcf814ea6e.png">

**Comment by akalata** [comment]
Yeah, it doesn't quite match the styles of the other ones. 

Here's the Simon Baz GL

![2571758-gbz4](https://cloud.githubusercontent.com/assets/1259018/11539122/0ff3d516-98eb-11e5-8e62-60b2e7b51253.jpg)

![2627787-baz1](https://cloud.githubusercontent.com/assets/1259018/11539140/2a17a260-98eb-11e5-9dae-7bfd255dabed.jpg)

**Comment by akalata** [comment]
https://www.stickermule.com/en/marketplace/11784-druplicon-green-lantern
